#!/bin/bash
# Run each script in the background
sbatch leafcutter_step_5_prepare_results_DPseq_sACC.sh
sbatch leafcutter_step_5_prepare_results_BPseq_sACC.sh
sbatch leafcutter_step_5_prepare_results_DPseq_Amygdala.sh
sbatch leafcutter_step_5_prepare_results_BPseq_Amygdala.sh
